<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="192-168-1-105.tpgi.com.au" ignored="0" name="Default test" tests="3" failures="1" timestamp="2021-04-26T10:48:25 AEST" time="44.078" errors="0">
  <testcase name="runScenario" time="14.626" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="15.939" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="12.661" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at com.automation.pages.CheckOutPage.verifyItemAdded(CheckOutPage.java:36)
at com.automation.stepDefinition.AddToCartTestcases.verifyOneItemAdded(AddToCartTestcases.java:64)
at âœ½.verify quantity 2 in checkout page(file:///Users/swathishetty/Documents/Swathi/Assignment/ecommerce/com.ecommerce/src/test/resources/features/AddToCart.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
